import initAccordion from "../../js/modules/accordion.js";
import initAnimacaoScroll from "../../js/modules/animacaoScroll.js";
import initScrollSuave from "../../js/modules/scrollSuave.js";
import initTabNav from "../../js/modules/tabNav.js";
import initModal from "../../js/modules/modal.js";
import initTooltip from "../../js/modules/toolltip.js";
import initDropdownMenu from "../../js/modules/dropdown-menu.js";
import initMenuMobile from "../../js/modules/menuMobile.js";
import initFuncionamento from "../../js/modules/funcionamento.js";
import initFetchAnimais from "../../js/modules/fetchAnimais.js";

initAccordion();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();